<?php // Emacs settings: -*- mode: Fundamental; tab-width: 4; -*-

////////////////////////////////////////////////////////////////////////////
//                                                                        //
// Minesweeper, implemented in JavaScript                                 //
//                                                                        //
// Copyright 1998-2007, Andrew D. Birrell                                 //
//                                                                        //
// PHP to generate the playing area HTML                                  //
//                                                                        //
// Usage:                                                                 //
//   $cols = 8;                                                           //
//   $rows = 8;                                                           //
//   require("minesweeper.php");                                          //
//                                                                        //
////////////////////////////////////////////////////////////////////////////

if (!isset($cols) || !isset($rows)) {
	exit("Minesweeper.php: missing parameter(s)");
}

?>
<!-- The following HTML is generated by a script.  See ./source.php -->
<TABLE ID=sqTable onmouseup="return false">
<TR><TD CLASS=score COLSPAN=<?php echo $cols?>>
<DIV CLASS=counter ID=mines>&nbsp;</DIV>
<DIV CLASS=counter ID=timer>&nbsp;</DIV>
<IMG ID=smiley SRC="erasing.gif" ALT=""
	onmousedown="return clickSmiley(event)">
</TD></TR>
<?php
	for ($row = 0; $row < $rows; $row++) { ?>
<TR>
<?php
		for ($col = 0; $col < $cols; $col++) { ?>
<TD CLASS=sq ID="sq-<?php echo $row * $cols + $col ?>"
  onmousedown="return clickSq(event,<?php echo $row * $cols + $col ?>)"
  >&nbsp;</TD>
<?php
		} ?>
</TR>
<?php
}
?>
</TABLE>
<!-- End of script-generated HTML -->